### PR TITLE
Node coordinate

### PR DESCRIPTION
**Pull request by vhirtham**
This PR is related to issue [#233](https://github.com/nutofem/nuto/issues/233). I implemented most things from the discussion. I skipped the separate interfaces for now, since I am not sure if it is necessary. 

In the ElementFEM class, I specialized two functions depending on the node type:

- `GetDofNumbering` will cause an assertion to fail, if you use it with coordinate nodes. I can also change it to an exception if you like that better. 
- `ExtractNodeValues` does basically the same for both specializations. Only difference is one naming related function call. I can put that function call into a separate function and specialize this one for maximum code re-usage, if you want.

I tried to use `std::enable_if` to avoid template specialization but since both functions are virtual, it is not possible or at least not trivial.

### CODE REVIEW

**Review by joergfunger — COMMENTED** [review]
The removal of the additional suffixes (simple,..) stemming from the parallel development with master is necessary. Furthermore, I believe that it makes sense to have a coordinate element and a dof-element, in particular when moving to a separate representation of the geometry with coordinate elements. The inclusion of some virtual methods in the coordinate element with an exception is suboptimal, but hopefully removed as soon as this geometry class is added.

**Comment by TTitscher** [comment]
As I said several times in the corresponding issue, I do not like this _old nuto_ style with virtual throw either. I think that the template approach is not suitable here. (What should TNode be, other than CoordinateNode or DofNode?) Two separate interfaces would be my preferred solution.

**Comment by vhirtham** [comment]
The problem here is, that separate classes do not solve the "throw" problem, cause the corresponding function is pure virtual in the elementInterace class. Even if you remove the template, you still have the "throw override" in the coordinate element. The ElementInterface itself is needed for the N and B Matrix. Solution might be to move the function to the derived classes out of the interface, but I am not sure if that works (without touching hundreds of lines of code).

**Comment by TTitscher** [comment]
Those separate classes may not have a common base. Or this common base has only common methods, like N, B or something. I mean, I can, again, refer to my first post in the issue, where I posted a sketch of what I would like. Maybe there is something wrong with that too, but you never really commented on it.

**Comment by pmueller2** [comment]
Group "Separate geometry and dofs/interpolation" decided to continue the work started here to separate CoordinateMesh and DofMesh as a first step towards a FunctionSpaceLike thing.

The pull request will (hopefully) be reopened when we are done.

**Pull request closed without merging**
